name = "bwb-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Performance update
[vars]

[[d1_databases]]
binding = "DB"
database_name = "bwb_memory"
database_id = "5420ff3e-324b-4c8d-b373-e3487ccb76ab"

[[kv_namespaces]]
binding = "BWB_NOTES"
id = "ccf58b9e7d474ba5bc1487678823dfc7"

[observability.logs]
enabled = false
invocation_logs = true